language: ruby
rvm:
- 2.0.0
cache:
  bundler: true
  directories:
  - node_modules
  - app/bower_components
before_install:
- git config credential.helper "store --file=.git/credentials"; echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials 2>/dev/null
- export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
- export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
- git config --global user.name "$AUTHOR_NAME"
- git config --global user.email "$COMMITTER_EMAIL"
before_script:
- nvm install 6
- bundle
- npm i -g bower
- bower i -f
- npm i
script:
- npm run gulp purge-cdn-cache
- npm run gulp 
deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master