language: ruby
rvm:
  - 2.0.0
cache:
  bundler: true
  directories:
    - node_modules
    - app/bower_components
before_script:
  - export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
  - git config --global user.name "$AUTHOR_NAME"
  - git config --global user.email "$COMMITTER_EMAIL"
  - nvm install 6
  - bundle
  - npm i -g bower
  - bower i -f
  - npm i
script:
  - npm run deploy
