language: ruby
rvm:
  - 2.0.0
cache:
  bundler: true
  directories:
    - node_modules
    - app/bower_components
before_script:
  - nvm install 6
  - bundle
  - npm i -g bower
  - bower i -f
  - npm i
script:
  - npm run deploy
