# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
title: ycfreeman's
google_analytics: UA-8760554-2

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: ycfreeman's
url: http://ycfreeman.com
name: 'ycfreeman&#039;s'
description: I play games, and I do code for food
author:
  name: ycfreeman
  email: freeman@ycfreeman.com
  github: ycfreeman
  linkedin: ycfreeman
  bio: I play games, and I do code for food
  email_md5: be91bc3f804140479ad043b33d25a8c5

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
