source: app
destination: app/_site

# Site settings
title: ycfreeman's
subtitle: I play games, and I do code for food
description:


author: Freeman Man
author_website: http://ycfreeman.com
email: freeman@ycfreeman.com

baseurl: "" # the subpath of your site, e.g. /blog. For deploying to github pages, this should match your repo name
url: "http://ycfreeman.com" # the base hostname & protocol for your site

twitter_username: ''
github_username:  ycfreeman
disqus_shortname: ''
linkedin: ycfreeman
google_analytics: UA-8760554-2

# Pagination
paginate: 5
paginate_path: "page:num"
excerpt_separator: <!--more-->

exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown

# Gems
gems:
  - jekyll-archives
  - jekyll-paginate
  - jemoji
  - jekyll-redirect-from

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

# Archive settings
jekyll-archives:
  enabled: ['tags']
