source: app
destination: app/_site

# Site settings
title: ycfreeman's
subtitle: I play games, and I do code for food
description:


author: Freeman Man
author_website: https://ycfreeman.com

baseurl: "" # the subpath of your site, e.g. /blog. For deploying to github pages, this should match your repo name
url: "https://ycfreeman.com" # the base hostname & protocol for your site

twitter_username: ''
github_username:  ycfreeman
disqus_shortname: ycfreeman
linkedin: ycfreeman
paypal: ycfreeman
google_analytics: UA-8760554-2

# Pagination
paginate: 5
paginate_path: "page/:num/"
excerpt_separator: <!--more-->

exclude: ["README.md"] # files to exclude
# keep_files: ["/wp-content/*"]
highlighter: rouge
markdown: kramdown

# Gems
gems:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-redirect-from
  - jemoji

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

# Archive settings
jekyll-archives:
  enabled: ['tags']

sitemap:
  exclude:
    - "/bower_components/*"
    - "/elements/*"
